name: build-and-test

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  thank-you-next:
    name: thank you, next
    runs-on: ubuntu-latest
    steps:
      - name: Fail for first 2 attempts, pass on 3rd
        shell: bash
        run: |
          echo "run_attempt = ${{ github.run_attempt }}"
          if [ "${{ github.run_attempt }}" != "3" ]; then
            echo "Intentionally failing (attempt ${{ github.run_attempt }})"
            exit 1
          fi
          echo "Passing on attempt 3"
          exit 0
